# Copyright 2026 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-releases
spec:
  serviceAccountName: release-automation
  triggers:
    - name: github-release-branch-webhook
      interceptors:
        - name: "Validate GitHub payload and filter on eventType"
          ref:
            name: "github"
            kind: ClusterInterceptor
          params:
            - name: "secretRef"
              value:
                secretName: release-webhook
                secretKey: secret
            - name: "eventTypes"
              value:
                - "push"
        - name: "Filter release branches"
          ref:
            name: "cel"
            kind: ClusterInterceptor
          params:
            - name: "filter"
              value: >-
                body.repository.full_name.startsWith('tektoncd/') &&
                body.ref.matches('refs/heads/release-v[0-9]+\\.[0-9]+\\.x')
            - name: "overlays"
              value:
                - key: release_branch
                  expression: "body.ref.split('/')[2]"
                - key: release_mode
                  expression: "'full-release'"
                - key: trigger_source
                  expression: "'webhook'"
        - name: "Add a build ID"
          ref:
            name: "build-id"
            kind: ClusterInterceptor
      bindings:
        - ref: release-branch-webhook
      template:
        ref: release-automation
    - name: cron-release-scanner
      interceptors:
        - name: "Filter cron triggers"
          ref:
            name: "cel"
            kind: ClusterInterceptor
          params:
            - name: "filter"
              value: >-
                'buildUUID' in body &&
                'params' in body &&
                'release' in body.params
      bindings:
        - ref: release-branch-cron
      template:
        ref: release-automation
    - name: github-chatops-commands
      interceptors:
        - name: "Validate GitHub payload and filter on eventType"
          ref:
            name: "github"
            kind: ClusterInterceptor
          params:
            - name: "secretRef"
              value:
                secretName: release-webhook
                secretKey: secret
            - name: "eventTypes"
              value:
                - "issue_comment"
        - name: "Filter release ChatOps commands"
          ref:
            name: "cel"
            kind: ClusterInterceptor
          params:
            - name: "filter"
              value: >-
                body.action == 'created' &&
                body.issue.labels.exists(l, l.name == 'automated-release') &&
                body.comment.body.startsWith('/release-')
            - name: "overlays"
              value:
                - key: command
                  expression: "body.comment.body.split(' ')[0].substring(1)"
                - key: issue_number
                  expression: "string(body.issue.number)"
                - key: repository_full_name
                  expression: "body.repository.full_name"
                - key: comment_author
                  expression: "body.comment.user.login"
      bindings:
        - ref: release-chatops-command
      template:
        ref: release-chatops
