apiVersion: batch/v1
kind: CronJob
metadata:
  name: scan-release-branches
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: create-taskrun
            env:
            - name: REPOSITORIES
              # Start with pipeline only, expand to triggers and operator later
              value: "tektoncd/pipeline"
            - name: EVENTLISTENER_URL
              value: "http://el-tekton-releases.automated-releases.svc.cluster.local:8080"
            - name: RELEASE_MODE
              value: "validation-only"
