# Copyright 2026 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Import existing GitHub resources into Terraform state.
#
# Org memberships can use for_each with a simple ID format (org:username).
# Team-related imports require numeric team IDs which must be resolved
# via the GitHub API. Use hack/generate-org-imports.sh to generate the
# team import blocks.
#
# After successful initial import, these blocks can be removed.

# --- Org membership imports ---
import {
  for_each = local.all_members
  to       = github_membership.this[each.key]
  id       = "tektoncd:${each.key}"
}

# --- Org settings import ---
import {
  to = github_organization_settings.tektoncd
  id = "tektoncd"
}

# --- Team, team membership, and team repository imports ---
# These are generated by hack/generate-org-imports.sh because they
# require numeric team IDs from the GitHub API.
#
# To generate:
#   cd terraform/org-management/tektoncd
#   ../../../hack/generate-org-imports.sh > imports-teams.tf
#
# The generated file contains import blocks for:
#   - github_team.this["team-name"]
#   - github_team_membership.this["team-name:username"]
#   - github_team_repository.this["team-name:repo"]
