apiVersion: v1
kind: ConfigMap
metadata:
  name: tekton-pruner-default-spec
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: tekton-pruner
    pruner.tekton.dev/config-type: global
data:
  global-config: |
    enforcedConfigLevel: namespace
    ttlSecondsAfterFinished: 604800
    successfulHistoryLimit: 30
    failedHistoryLimit: 10
    namespaces:
      tekton-ci:
        ttlSecondsAfterFinished: 259200
        successfulHistoryLimit: 20
        failedHistoryLimit: 10
