#!/usr/bin/env bash
# Copyright 2026 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generate Terraform import blocks for tektoncd org team resources.
#
# This script queries the GitHub API to resolve team slugs to numeric IDs,
# then generates import blocks for:
#   - github_team
#   - github_team_membership
#   - github_team_repository
#
# Usage:
#   cd terraform/org-management/tektoncd
#   ../../../hack/generate-org-imports.sh > imports-teams.tf
#
# Prerequisites:
#   - gh CLI authenticated with admin:org scope for tektoncd
#   - jq

set -euo pipefail

ORG="${1:-tektoncd}"

# Check prerequisites
for cmd in gh jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "Error: $cmd is required but not found" >&2
    exit 1
  fi
done

cat <<EOF
# Auto-generated import blocks for ${ORG} org team resources.
# Generated on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# This file is generated by hack/generate-org-imports.sh.
# After successful initial import, both this file and imports.tf
# can be removed.

EOF

echo "# --- Team imports ---"
echo ""

# Fetch all teams and build a slug→id map
TEAMS_JSON=$(gh api --paginate "/orgs/${ORG}/teams" --jq '.')

# Note: peribolos uses dots in team names (e.g. "pipeline.maintainers")
# but GitHub stores the slug with dots replaced by hyphens. The Terraform
# resource key uses the peribolos name (from org.yaml), so we need to
# map from slug back to the dotted name for the resource address.
#
# However, the GitHub Terraform provider uses the team's numeric ID
# internally, and we create teams by name. So the for_each key in our
# terraform is the peribolos name (e.g. "pipeline.maintainers").
#
# For import, we need the numeric ID. GitHub API returns the slug
# (e.g. "pipeline-maintainers"), which we need to map back to the
# peribolos name. The mapping is: replace hyphens with dots where
# the original had dots.
#
# Since this is a one-time operation, we output both and let the
# operator verify the mapping.

echo "$TEAMS_JSON" | jq -r '.[] | @json' | while IFS= read -r team_json; do
  team_id=$(echo "$team_json" | jq -r '.id')
  team_slug=$(echo "$team_json" | jq -r '.slug')
  team_name=$(echo "$team_json" | jq -r '.name')

  # Use the team name as the Terraform key (matches org.yaml)
  cat <<EOF
import {
  to = github_team.this["${team_name}"]
  id = "${team_id}"
}

EOF

  # Fetch team members
  members_json=$(gh api --paginate "/orgs/${ORG}/teams/${team_slug}/members" --jq '.' 2>/dev/null || echo '[]')
  echo "$members_json" | jq -r '.[] | .login' | while IFS= read -r username; do
    # Determine role (maintainer or member)
    role=$(gh api "/orgs/${ORG}/teams/${team_slug}/memberships/${username}" --jq '.role' 2>/dev/null || echo "member")
    cat <<EOFM
import {
  to = github_team_membership.this["${team_name}:${username}"]
  id = "${team_id}:${username}"
}

EOFM
  done

  # Fetch team repositories
  repos_json=$(gh api --paginate "/orgs/${ORG}/teams/${team_slug}/repos" --jq '.' 2>/dev/null || echo '[]')
  echo "$repos_json" | jq -r '.[] | .name' | while IFS= read -r repo_name; do
    cat <<EOFR
import {
  to = github_team_repository.this["${team_name}:${repo_name}"]
  id = "${team_id}:${repo_name}"
}

EOFR
  done
done
