apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/tektoncd/pipelines-as-code/releases/download/v0.45.0/release.k8s.yaml
- ingress.yaml
- repositories/pipeline.yaml
- repositories/operator.yaml
- repositories/cli.yaml
patches:
- path: pipelines-as-code-configmap.yaml
