apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/task.yaml
  - hold
  - kind
  - priority
  - area
  - help
  - good-first-issue
  - assign
  - cc
  - retitle
  - milestone
